//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1 {
    public partial class OrderHistory {
        /// <summary>
        /// gvOrderHistory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvOrderHistory;
        /// <summary>
        /// btnBackHome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBackHome;
    }
}
